// Bootstrap checked-in types without creating a cloud project or requiring credentials.
// Uses the installed Convex version's official templates. Normal `convex dev` replaces these.
import { mkdir, writeFile, readdir } from "node:fs/promises";
const templateDirectory = "../node_modules/convex/src/cli/codegen_templates/";
const { apiCodegen } = await import(templateDirectory + "api.ts");
const { serverCodegen } = await import(templateDirectory + "server.ts");
const moduleFiles = (await readdir("convex")).filter(file => file.endsWith(".ts") &&
  !file.endsWith(".d.ts") && !file.endsWith(".test.ts") && !["schema.ts", "crons.ts", "auth.config.ts"].includes(file)).sort();
const api = apiCodegen(moduleFiles);
const server = serverCodegen({ useTypeScript: false, envVars: undefined });
await mkdir("convex/_generated", { recursive: true });
await Promise.all([
  writeFile("convex/_generated/api.js", api.JS!), writeFile("convex/_generated/api.d.ts", api.DTS!),
  writeFile("convex/_generated/server.js", server.JS!), writeFile("convex/_generated/server.d.ts", server.DTS!),
  writeFile("convex/_generated/dataModel.d.ts", `/* Bootstrap schema-derived types. Regenerated by convex dev. */
import type { DataModelFromSchemaDefinition, DocumentByName, TableNamesInDataModel, SystemTableNames } from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema";
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type TableNames = TableNamesInDataModel<DataModel>;
export type Doc<TableName extends TableNames> = DocumentByName<DataModel, TableName>;
export type Id<TableName extends TableNames | SystemTableNames> = GenericId<TableName>;
`),
]);
console.log("Offline Convex bootstrap types generated; no cloud deployment changed.");
