import type { DealView } from "./deals";

/** Fictional presentation data. Never submitted, mixed into, or labeled live. */
export const demoDeals: DealView[] = [
  {
    id: "demo-ramen",
    restaurant: "Nori Noodle House",
    dealText: "A warm bowl. A small bill.",
    description:
      "Rich miso ramen with spring onions and a soft egg. A fictional offer for the design preview.",
    priceCad: 8.5,
    originalPrice: 15,
    currency: "CAD",
    address: "Sample restaurant · Vancouver",
    validDays: [],
    validStart: "11:00",
    validEnd: "23:00",
    conditions: ["Dine-in only", "One bowl per person"],
    createdAt: 6,
    imageUrl: "/images/ramen.jpg",
    imageAlt: "A bowl of miso ramen with egg and spring onions",
    authorName: "Sample community",
    stillOnCount: 12,
    expiredCount: 0,
    isDemo: true,
  },
  {
    id: "demo-pizza",
    restaurant: "Corner Slice",
    dealText: "Two slices, one happy lunch.",
    description:
      "Two slices of cheese pizza, fresh from the oven. A fictional offer for the design preview.",
    priceCad: 5,
    originalPrice: 9,
    currency: "CAD",
    address: "Sample restaurant · Burnaby",
    validDays: [],
    validStart: "11:00",
    validEnd: "23:00",
    conditions: ["Selected slices", "While supplies last"],
    createdAt: 5,
    imageUrl: "/images/pizza.jpg",
    imageAlt: "Golden cheese pizza slices topped with basil",
    authorName: "Sample community",
    stillOnCount: 8,
    expiredCount: 1,
    isDemo: true,
  },
  {
    id: "demo-sushi",
    restaurant: "Little Bento",
    dealText: "Your lunch break, rolled up.",
    description:
      "A colourful sushi set with fresh rolls and pickled ginger. A fictional offer for the design preview.",
    priceCad: 9.5,
    originalPrice: 16,
    currency: "CAD",
    address: "Sample restaurant · Vancouver",
    validDays: [],
    validStart: "11:00",
    validEnd: "23:00",
    conditions: ["Takeout only"],
    createdAt: 4,
    imageUrl: "/images/sushi.jpg",
    imageAlt: "A sushi set with salmon rolls and pickled ginger",
    authorName: "Sample community",
    stillOnCount: 19,
    expiredCount: 0,
    isDemo: true,
  },
  {
    id: "demo-coffee",
    restaurant: "Daylight Coffee",
    dealText: "A little pick-me-up for less.",
    description:
      "A freshly brewed latte for your next study break. A fictional offer for the design preview.",
    priceCad: 3.5,
    originalPrice: 6,
    currency: "CAD",
    address: "Sample café · Burnaby",
    validDays: [],
    validStart: "07:00",
    validEnd: "23:00",
    conditions: ["Regular size", "Dairy alternatives extra"],
    createdAt: 3,
    imageUrl: "/images/coffee.jpg",
    imageAlt: "A latte with leaf-shaped foam art in a ceramic cup",
    authorName: "Sample community",
    stillOnCount: 6,
    expiredCount: 0,
    isDemo: true,
  },
  {
    id: "demo-tacos",
    restaurant: "Mesa Taco Club",
    dealText: "Big flavour. Little price.",
    description:
      "Two tacos with crisp vegetables, lime, and salsa. A fictional offer for the design preview.",
    priceCad: 7,
    originalPrice: 12,
    currency: "CAD",
    address: "Sample restaurant · Vancouver",
    validDays: [],
    validStart: "11:00",
    validEnd: "23:00",
    conditions: ["Choice of filling", "Dine-in or takeout"],
    createdAt: 2,
    imageUrl: "/images/tacos.jpg",
    imageAlt: "Two tacos with fresh vegetables, coriander, and lime",
    authorName: "Sample community",
    stillOnCount: 15,
    expiredCount: 0,
    isDemo: true,
  },
  {
    id: "demo-burger",
    restaurant: "The Good Bun",
    dealText: "A proper burger, pocket change.",
    description:
      "A classic burger with crisp lettuce and a toasted bun. A fictional offer for the design preview.",
    priceCad: 10,
    originalPrice: 17,
    currency: "CAD",
    address: "Sample restaurant · Richmond",
    validDays: [],
    validStart: "11:00",
    validEnd: "23:00",
    conditions: ["Burger only", "Add-ons extra"],
    createdAt: 1,
    imageUrl: "/images/burger.jpg",
    imageAlt: "A burger with a toasted bun, lettuce, and tomato",
    authorName: "Sample community",
    stillOnCount: 10,
    expiredCount: 1,
    isDemo: true,
  },
];
